lambdas:

    resolveissue-init:
        code: resolveissue-init
        handler: code.lambda_handler
        runtime: python
        build:
        - cp -Rf * {target}
        - cp -Rf {project_path}\common\* {target}
        - echo "[install]\nprefix=" > {target}/setup.cfg
        - "{pip_path} install -r requirements.txt -q -t {target} {pip_install_extra}"
        - cd {target} && find . -name "*.pyc" -delete
        #description: Checks for resolutions of issue from existing entries in database else fetches links to resolution from stackoverflow
        #role:
        #memory:
