lambdas:

    assign-init:
        code: assign-init
        handler: code.lambda_handler
        runtime: python
        build:
        - cp -Rf * {target}
        - cp -Rf {project_path}\common\* {target}
        - echo "[install]\nprefix=" > {target}/setup.cfg
        - "{pip_path} install -r requirements.txt -q -t {target} {pip_install_extra}"
        - cd {target} && find . -name "*.pyc" -delete
        #description: assign runbook from session or from slot to another user
        #role:
        #memory:

    assign-fulfill:
        code: assign-fulfill
        handler: code.lambda_handler
        runtime: python
        build:
        - cp -Rf * {target}
        - cp -Rf {project_path}\common\* {target}
        - echo "[install]\nprefix=" > {target}/setup.cfg
        - "{pip_path} install -r requirements.txt -q -t {target} {pip_install_extra}"
        - cd {target} && find . -name "*.pyc" -delete
        #description: assign runbook from session or from slot to another user
        #role:
        #memory:
        